main: main.o
				g++ main.o -o main
main.o:main.cpp
				g++ -c main.cpp -o main.o

#main: main.o layer.o
#				g++ main.o layer.o -o main
#layer.o:layer.cpp
#				g++ -c layer.cpp -o layer.o
#main.o:main.cpp
#				g++ -c main.cpp -o main.o
